ALTER TABLE kds_config
ADD COLUMN IF NOT EXISTS voice_enabled BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS voice_label TEXT,
ADD COLUMN IF NOT EXISTS voice_repeat BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS voice_include_total BOOLEAN DEFAULT true;

