ALTER TABLE printers ADD COLUMN IF NOT EXISTS usb_vendor_id INTEGER;
ALTER TABLE printers ADD COLUMN IF NOT EXISTS usb_product_id INTEGER;
ALTER TABLE printers ADD COLUMN IF NOT EXISTS is_default BOOLEAN DEFAULT false;
