ALTER TABLE printers ADD COLUMN IF NOT EXISTS ticket_header TEXT DEFAULT '';
ALTER TABLE printers ADD COLUMN IF NOT EXISTS ticket_footer TEXT DEFAULT '';
ALTER TABLE printers ADD COLUMN IF NOT EXISTS comanda_header TEXT DEFAULT '';
ALTER TABLE printers ADD COLUMN IF NOT EXISTS comanda_footer TEXT DEFAULT '';
